spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/part_time_db
    url: jdbc:postgresql://dpg-csc86dtds78s738kevg0-a.singapore-postgres.render.com:5432/part_time_server_db?user=parttimejobs&password=QnPhcYd2WFiIWIYiFMrvqONLBUWbavDb
    username: jobs
    password: "KjUsXBLxW0pyGHgBSQSS3IZ97916ilJQ"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8080